---
ansible_user: vagrant
ansible_password: "{{ vault_ansible_password }}"
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
welcome: Bienvenue Ã   {{ ansible_hostname }}
afip: MPI Info 2021 2022
